### ISSUE TITLE
Proposal: support degradation config for Kitex server

### ISSUE THREAD

**Issue by felix021** [kitex-contrib/config-nacos#24]
Please help add "degradation" as a new type of service governance config to these extensions, instructing Kitex **clients** to drop the corresponding percentile of requests, which is helpful when the server is confronted with an overwhelming amount of traffic.

For example, the config value may be:

```json
{
    "enabled": true,
    "percentage": 50
}
```

Meaning the server should drop 50% of the traffic.
The default value should be `{"enabled": false}` to avoid loss.

Note that Kitex provides a builtin ACL mechanism by `client.WithACLRules`, which is helpful to implement the degradation policy.

Please prepare a tech plan (lark doc) for this task, including the background, goal, your design details and any problems for discussion before proceeding to the coding phase.

**Comment by Madxf** [comment]
I wanna try it
